# Generated by Django 6.0.6 on 2026-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_cmscontent_delete_chathistory_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MBA Programme', max_length=200)),
                ('overview', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('eligibility', models.TextField()),
                ('career_opportunities', models.TextField()),
            ],
        ),
    ]
