# Generated by Django 6.0.6 on 2026-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('COMMON', 'Common'), ('FINANCE', 'Finance'), ('HRM', 'Human Resource Management'), ('MARKETING', 'Marketing')], default='COMMON', max_length=20)),
                ('semester', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II'), ('III', 'Semester III'), ('IV', 'Semester IV')], max_length=10)),
                ('course_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
