# Generated by Django 6.0.6 on 2026-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_event_faculty_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
